name: Update rclgo-msgs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  update-rclgo-msgs:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout fog_msgs
        uses: actions/checkout@v2
        with:
          path: fog_msgs

      - name: Checkout rclgo-msgs
        uses: actions/checkout@v2
        with:
          path: rclgo-msgs
          repository: tiiuae/rclgo-msgs
          token: ${{ secrets.RCLGO_MSGS_DEPLOY_KEY }}

      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Generate and push bindings
        run: ./rclgo-msgs/.tools/generate-package.sh fog_msgs rclgo-msgs
